### ISSUE TITLE
Pagination not working in ServerDataSource

### ISSUE THREAD

**Issue by william-levi** [dj-fiorex/angular2-smart-table#89] opened 2022-07-05 06:48 UTC
using serverDatasource pagination not working
```typescript
this.source = new ServerDataSource(this._http, {
      endPoint: `${environment.baseUrl}/admin/users`,
      dataKey: "data",
      pagerPageKey: "page",
      pagerLimitKey: "pageSize",
      totalKey: "total",
    });
```

**Comment by uap-universe** [comment] 2022-07-05 12:13
What _exactly_ is not working?
* Are the pagination controls not displayed?
* Is the request not submitted?
* Are the request contents wrong (in particular: the query parameters)?
* Is the response not correctly processed?
* Is the response correctly processed, but the data is not displayed? (In other words: is it just that the table does not visually refresh?)

**Comment by uap-universe** [comment] 2022-09-09 12:15
Since apparently there is not coming more information from the OP, I try to investigate towards Milestone 2.7.0 but if I cannot reproduce the issue, I am going to close it.

**Comment by PandaxZA** [comment] 2022-09-28 13:17
I have just stumbled across this same issue. 
Pagination controls are not being displayed. 

Total > PageSize at this point

**Comment by PandaxZA** [comment] 2022-09-28 13:37
Edit: I have found the issue, and a temporary solution. 

https://github.com/dj-fiorex/angular2-smart-table/blob/42f5f4e7b5c047e59c7cac9605af0c8609e3cb10/projects/angular2-smart-table/src/lib/lib/data-source/server/server.data-source.ts#L26

`this.source.count()` within the pager component is not passing the boolean `total` affecting:
```
  override count(total: boolean = false): number {
    return total ? this.lastRequestCount : this.data.length;
  }
```

This can be resolved with:

```
override count() {
        return this.lastRequestCount
    }
```

**Comment by uap-universe** [comment] 2022-10-04 10:55
@PandaxZA thank you. But the fix you provided is not really a fix, because it changes the condition for showing the pagination even for local data sources.

The condition is: the total **displayed** rows is larger than what would fit on a page.

In the local data source this is the length of the `filteredAndSorted` array and in the server data source it _actually_ is the length of the data array (as this is already filtered and sorted by the server).

So the real issue seems to be that the data array is not initialized (yet) when `count` is called.

I know that the original authors were a bit careless, to say the least, when they implemented the `ServerDataSource` - I have already fixed some stuff there. But when doing so, we should make sure not to break the "working" stuff.

**Comment by PandaxZA** [comment] 2022-10-05 06:13
@uap-universe thanks for this feedback. 
I totally agree. 

Happy to have the override available for someone to use in the meantime, but the dataSource will need to be changed at some point.

**Comment by miguel2211** [comment] 2022-10-23 02:29
Hello, maybe this question is annoying, but I've been trying to get a solution for several hours, how do you override?

**Comment by uap-universe** [comment] 2022-10-25 07:35
No, of course it is not annoying. Next time, don't waste hours and ask directly :)

You would need to use a local copy of the lib or reference PandaxZA's fork in your package.json. This is rather complicated, so I suggest as an easy workaround that does require patching the smart table implementation, just invoke `refresh()` on the data source after the data has been fetched from the server. A dirty way of doing this would be a `setTimeout(() => this.source.refresh(), 200)` in onInit hoping for the best, but this is really dirty.

The `refresh()` call results in the data source emitting a `change` event, which the pagination is subscribed to. The pagination will then update its state with the latest information in the data source. Other than that, the `refresh()` call has no side effect and should be the cheapest way to trick the pagination into updating the information on the `count()`.

I dived into the code and I suspect that exactly this `change` event is missing in the server data source after loading the data. If the data source sent that event, that would (I think) actually solve the problem. I try that for the next release.

**Comment by uap-universe** [comment] 2022-10-27 08:07
Short update: by taking a more closer look at the implementation, it turned out, that the implementation of `count()` is wrong and it could never be correct, because the `ServerDataSource` does never receive something like the "total number of elements, regardless of the filter". The total from the point of view of the `ServerDataSource` is always with respect to the filter.

I have pushed a solution by applying the fix suggested by @PandaxZA in [this comment](https://github.com/dj-fiorex/angular2-smart-table/issues/89#issuecomment-1260929557) to the master branch, it will be released very soon.

If anyone is currently using `count(true)` because you are really interested in the total number of elements *regardless* of the filter, you might be able to replace that with `(await source.getAll()).length` or `source.getAll().then(data => this.total = data.length)` for example.

**Closed** 2022-10-27 08:07 UTC
Labels: bug

**Comment by PandaxZA** [comment] 2022-10-27 09:35
@uap-universe Thanks for taking the time to check this. Appreciate it 👍
